# This is the network config written by 'subiquity'
network:
  ethernets:
    ens18:
      addresses:
      - 10.254.251.21/24
      nameservers:
        addresses:
        - 10.254.251.1
        search:
        - cabecasa.net
      routes:
      - to: default
        via: 10.254.251.1
  version: 2
