---
- name: "Staging collector" 
  hosts: "staging"
  remote_user: mcabe
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  tasks:
  
     # run apt update
     - name: Running apt update
       ansible.builtin.apt:
         update_cache: yes
  
     # run apt upgrade
     - name: Running apt upgrade
       ansible.builtin.apt:
         name: "*"
         state: latest
  
     # run apt update distro
     - name: Running apt dist-upgrade
       ansible.builtin.apt:
         upgrade: dist
  
     # run apt autormove
     - name: Running apt autoremove
       ansible.builtin.apt:
         autoremove: yes
  
     - name: Installing application
       ansible.builtin.apt:
         pkg:
           - apt-transport-https
           - ca-certificates
           - curl
           - net-tools
           - conntrack
           - snmp
           - python3-pexpect
           - docker
           - docker.io
           - mlocate
           - sshpass
           - nmap
           - tmux
           - python3-pip
         state: present
         update_cache: yes
         autoremove: yes

    - name: Copy hosts file
      copy:
        src: ./hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644 
      become: true

    - name: Copy hostname file
      copy:
        src: ./hostname
        dest: /etc/hostname
        owner: root
        group: root
        mode: 0644 
      become: true

    - name: Copy netplan file
      copy:
        src: ./00-installer-config.yaml
        dest: /etc/netplan/00-installer-config.yaml
        owner: root
        group: root
        mode: 0644 
      become: true
      
    - name: Unconditionally shut down the machine with all defaults
      community.general.shutdown:

